# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, DESKTOP-SEONGKYU]

    env:
      PLATFORM: x86
      CONFIGURATION: Release
      SLN_FILE: GetDiskNumber.sln

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up VS2010 environment
      shell: cmd
      run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" %PLATFORM%

    - name: Build full solution
      shell: cmd
      run: |
          "C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" %SLN_FILE% /p:Configuration=%CONFIGURATION%;Platform=%PLATFORM% /m

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
          name: All Build Outputs
          path: |
            **/Release/*.exe
            **/Release/*.dll
